[package]
name = "ingress_intel_rs"
version = "0.4.0"
authors = ["Marco Napetti <marco.napetti@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.6", features = ["cookies", "json", "gzip"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.71"
once_cell = "1.8.0"
tracing = "0.1.29"
regex = "1.5.4"
percent-encoding = "2.1.0"

[dev-dependencies]
tokio = { version = "1.14.0", features = ["macros"] }
tracing-subscriber = { version = "0.3.1", features = ["env-filter"] }
