[package]
name = "ingress_intel_rs"
version = "0.5.0"
authors = ["Marco Napetti <marco.napetti@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.9", features = ["cookies", "json", "gzip"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
once_cell = "1.9.0"
tracing = "0.1.29"
regex = "1.5.4"
percent-encoding = "2.1.0"
tokio = { version = "1.15.0", features = ["sync"] }

[dev-dependencies]
tokio = { version = "1.15.0", features = ["sync", "macros"] }
tracing-subscriber = { version = "0.3.7", features = ["env-filter"] }
