[package]
name = "ingress_intel_rs"
version = "0.6.0"
authors = ["Marco Napetti <marco.napetti@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.10", features = ["cookies", "json", "gzip"] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
once_cell = "1.10.0"
tracing = "0.1.32"
regex = "1.5.5"
percent-encoding = "2.1.0"
tokio = { version = "1.17.0", features = ["sync"] }

[dev-dependencies]
tokio = { version = "1.17.0", features = ["sync", "macros"] }
tracing-subscriber = { version = "0.3.9", features = ["env-filter"] }
