[package]
name = "ingress_intel_rs"
version = "0.7.0"
authors = ["Marco Napetti <marco.napetti@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.12", features = ["cookies", "json", "gzip"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
once_cell = "1.16.0"
tracing = "0.1.37"
regex = "1.7.0"
percent-encoding = "2.2.0"
tokio = { version = "1.21.2", features = ["sync", "time"] }

[dev-dependencies]
tokio = { version = "1.21.2", features = ["sync", "macros", "time"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
