[package]
name = "ingress_intel_rs"
version = "0.3.1"
authors = ["Marco Napetti <marco.napetti@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["cookies", "json", "gzip"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.5"
log = "0.4"
regex = "1.4"
percent-encoding = "2.1"

[dev-dependencies]
tokio = { version= "1", features = ["macros"] }
env_logger = "0.8"
